config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end

  resources :charges, only: [:new, :create]


  root 'wikis#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wikis

  after_initialize{ self.role ||= :standard }

  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create

    if current_user.standard?
      customer = Stripe::Customer.create(
        email: current_user.email,
        card: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: 10_00,
        description: "BigMoney Membership - #{current_user.email}",
        currency: 'usd'
      )

      flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
      current_user.premium!
      redirect_to wikis_path

    else
      current_user.wikis.update_all(private: false)
      current_user.standard!
      redirect_to edit_user_registration_path
    end

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path

  end

  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key]}",
      description: "BigMoney Membership - #{current_user.email}",
      amount: 10_00
    }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  before_action :set_wiki

  def index
    @users = User.all
  end

  def create
    @collaborator = @wiki.collaborators.create(user_id: params[:user_id])

    if @collaborator.save
      flash[:notice] = "Collaborator was added."

    else
      flash.now[:alert] = "There was an error adding the collaborator. Please try again."

    end
    redirect_to wiki_collaborators_path(@wiki)
  end

  def destroy
    @user = @wiki.users.find(params[:id])
    @collaborator = @wiki.collaborators.find_by(user_id: @user.id)

    if @collaborator.destroy
      flash[:notice] = "\"#{@collaborator}\" was removed successfully."
    else
      flash.now[:alert] = "There was an error removing the collaborator."
    end
    redirect_to wiki_collaborators_path(@wiki)
  end

  private
  def collab_params
    params.require(:collaborator).permit(:wiki_id, :user_id)
  end

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_wiki, except: [:index, :new, :create]

  def show
    authorize @wiki
  end

  def index
    @wikis = policy_scope(Wiki)
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    authorize @wiki
  end

  def update
    authorize @wiki

    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error updating the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

  def set_wiki
    @wiki = Wiki.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank"},
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink: true,
      superscript: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">
      <h1>The Perks of Premium</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <h3><%= Faker::Hipster.sentence(3) %></h3>
      <p><%= Faker::Hipster.paragraph(3) %></p>
    </div>
    <div class="col-md-4">
      <h3><%= Faker::Hipster.sentence(5) %></h3>
      <p><%= Faker::Hipster.paragraph(2) %></p>
    </div>
    <div class="col-md-4">
      <h3><%= Faker::Hipster.sentence(4) %></h3>
      <p><%= Faker::Hipster.paragraph(4) %></p>
    </div>
  </div>

  <div class="row">
    <div class="text-center">
      <%= form_tag charges_path do %>
        <h4>Upgrade Now!</h4>
        <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
      <% end %>
    </div>
  </div>
</div>

app/views/collaborators/index.html.erb
<h1>Manage Collaborators for <%= @wiki.title %></h1>

<table class="table">
  <thead>
    <th>
      Email
    </th>
    <th>
      Add/Remove
    </th>
  </thead>


  <% @users.each do |user| %>
    <tr>
      <td>
        <%= user.email %>
      </td>
      <td>
        <% if @wiki.users.include?(user) %>
          <%= link_to "-", wiki_collaborator_path(@wiki, user), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to "+", {controller: "collaborators", action: "create", wiki_id: @wiki.id, user_id: user.id}, method: :post, class: 'btn btn-success' %>
        <% end %>
      </td>
    </tr>
  <% end %>


</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codapedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="pull-right">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.email %></strong>
            <%= link_to "Edit profile", edit_user_registration_path, class: 'btn btn-primary' %> |
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> |
            <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %>
            <% end %>
        </div>
      </div>


      <%= yield %>

    </div>

    <script src="https://js.stripe.com/v3/"></script>
  </body>
</html>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(wiki.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(wiki.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  <% end %>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private Wiki
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
    <% if @wiki.private? && @wiki.user == current_user %>
        <%= link_to "Manage Collaborators", wiki_collaborators_path(@wiki), class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>
      Guidelines for wikis
    </p>
    <ul>
      <li>Wikis are public, no foul language.</li>
      <li>Cite your sources.</li>
      <li>Spread your knowledge.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: {wiki: @wiki} %>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="wiki-index">
  <h1>Wikis</h1>

  <div class="row">
    <div class="col-md-8">
      <% @wikis.each do |wiki| %>
          <div class="media">
            <div class="media-body">
              <h4 class="media-heading">
                <%= link_to wiki.title, wiki %>
              </h4>
              <small>
                <%= markdown(wiki.body) %>
              </small>
            </div>
          </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <% if policy(Wiki).new? %>
        <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>
      Guidelines for wikis
    </p>
    <ul>
      <li>Wikis are public, no foul language.</li>
      <li>Cite your sources.</li>
      <li>Spread your knowledge.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: {wiki: @wiki} %>
  </div>
</div>

app/views/wikis/show.html.erb
<div>
  <h1><%= @wiki.title %><br />
    <small>
      submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %>
    </small>
  </h1>
</div>

<div class="row">
  <div class="col-md-8">
    <p>
      <%= markdown(@wiki.body) %>
    </p>
  </div>
</div>

<% if @wiki.private? %>
  <h3>Wiki Collaborators:</h3>
  <ul>
    <% @wiki.users.each do |collaborator| %>
      <li><%= collaborator.email %></li>
    <% end %>
  </ul>
<% end %>

<div lass="col-md-4">
  <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
  <% if @wiki.user == current_user %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this wiki?"}%>
  <% end %>
</div>